### ISSUE TITLE
Image sort by date appears to sort dates as strings

### ISSUE THREAD

**Issue by hwine** [MozillaSecurity/virgo#13]
- **Version**: 0.2.2
- **Platform**: Win10

In the Virgo dashboard, sorting the docker images by date shows the dates are treated as strings, not dates. That'd be fine if the dates were displayed per RFC-3339, but they aren't (even though that is the format I've configured Windows to use):
![image](https://user-images.githubusercontent.com/132412/60762424-548fa180-a014-11e9-9070-90944635da29.png)

**Comment by posidron** [comment]
True, that needs to be fixed. Thanks for pointing that out.

**Comment by posidron** [comment]
Fixed in https://github.com/MozillaSecurity/virgo/commit/6d79cc39d403def9bc8c89146783233822e9bc9d
