### ISSUE TITLE
Timer code is off when running for more than 2h

### ISSUE THREAD

**Issue by padenot** [MozillaSecurity/virgo#14]
- **Version**: 0.2.2
- **Platform**: Linux

![1562597444](https://user-images.githubusercontent.com/270485/60821623-35c01500-a1a4-11e9-85c6-476e11110725.png)

**Comment by posidron** [comment]
The spinner should not be visible either, we are in some weird state here.

Besides the Timer,
- [ ] Is the status still saying that the Task is running?
- [ ] Did you close / reopen the app while a task was running?
- [ ] Did you went to the Preferences / Activity views while the task was running?

**Comment by posidron** [comment]
Identified the Timer issue though, will work on a fix.

```
  getUnits = timeElapsed => {
    const seconds = timeElapsed / 1000
    return {
      hh: Math.floor(seconds / 60 / 60).toString(),
      min: Math.floor(seconds / 60).toString(),
      sec: Math.floor(seconds % 60).toString()
    }
  }
```

3500000 - {"hh":"0","min":"58","sec":"20"} 
3600000 - {"hh":"1","min":"60","sec":"0"}

**Comment by padenot** [comment]
> Is the status still saying that the Task is running?

I don't remember

> Did you close / reopen the app while a task was running?

Probably, yes.

> Did you went to the Preferences / Activity views while the task was running?

Yes.

**Comment by posidron** [comment]
Okay, closing this, since the original issue is fixed. The updater should provide you with a new version. Alternatively: https://github.com/MozillaSecurity/virgo/releases/download/v0.2.3/virgo-0.2.3-linux-x86_64.AppImage

Thanks for testing it!
